module.exports = {
  darkMode: 'class',
  content: ['./_*/code.html'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dadada',
        'on-secondary-fixed-variant': '#004493',
        'primary-fixed': '#66ff95',
        'on-tertiary-fixed-variant': '#6a3b00',
        'inverse-on-surface': '#f1f1f1',
        'surface-container': '#eeeeee',
        'outline-variant': '#bbcbba',
        'primary-container': '#07c160',
        'on-surface-variant': '#3d4a3d',
        'surface-tint': '#006d33',
        'inverse-surface': '#2f3131',
        'tertiary-container': '#f58f00',
        'surface-variant': '#e2e2e2',
        background: '#f9f9f9',
        'secondary-fixed-dim': '#adc6ff',
        'on-surface': '#1a1c1c',
        'secondary-fixed': '#d8e2ff',
        'surface-container-high': '#e8e8e8',
        'tertiary-fixed': '#ffdcbf',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        tertiary: '#8c5000',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#2d1600',
        'on-primary-fixed-variant': '#005225',
        outline: '#6c7b6c',
        'surface-container-lowest': '#ffffff',
        secondary: '#0058bc',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        primary: '#006d33',
        error: '#ba1a1a',
        'primary-fixed-dim': '#45e17c',
        'on-background': '#1a1c1c',
        'on-primary-fixed': '#00210b',
        'inverse-primary': '#45e17c',
        'secondary-container': '#0070eb',
        'error-container': '#ffdad6',
        surface: '#f9f9f9',
        'surface-container-highest': '#e2e2e2',
        'surface-container-low': '#f3f3f3',
        'on-tertiary-container': '#5d3300',
        'on-secondary-container': '#fefcff',
        'on-primary-container': '#00471f',
        'surface-bright': '#f9f9f9',
        'tertiary-fixed-dim': '#ffb874',
        'on-secondary-fixed': '#001a41',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '12px',
        margin: '16px',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans', 'PingFang SC', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'PingFang SC', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'PingFang SC', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'PingFang SC', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'PingFang SC', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'PingFang SC', 'sans-serif'],
        'label-md': ['Be Vietnam Pro', 'PingFang SC', 'sans-serif'],
        'label-sm': ['Be Vietnam Pro', 'PingFang SC', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm-mobile': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
};
