const locations = [
  {
    id: 1,
    name: '搬家一号箱',
    type: 'box',
    path: '储物间 1',
    itemCount: 12,
    coverUrl: '/assets/images/image-01.jpg',
    heroUrl: '/assets/images/image-01.jpg',
    updatedLabel: '2天前',
    tags: ['搬家', '储物'],
    children: [],
  },
  {
    id: 2,
    name: '冬季衣物',
    detailTitle: '冬季收纳四号',
    detailLocation: '阁楼 - 二排二层',
    type: 'box',
    path: '主卧衣柜',
    itemCount: 8,
    detailItemCount: 12,
    coverUrl: '/assets/images/image-02.jpg',
    heroUrl: '/assets/images/image-07.jpg',
    updatedLabel: '5天前',
    detailUpdatedLabel: '2天前',
    tags: ['衣物', '季节', '易损'],
    children: [],
  },
  {
    id: 3,
    name: '数码配件',
    type: 'box',
    path: '办公室架子',
    itemCount: 24,
    coverUrl: '/assets/images/image-03.jpg',
    heroUrl: '/assets/images/image-03.jpg',
    updatedLabel: '1周前',
    tags: ['数码', '办公'],
    children: [],
  },
  {
    id: 4,
    name: '旧书收藏',
    type: 'box',
    path: '阁楼二区',
    itemCount: 15,
    coverUrl: '/assets/images/image-04.jpg',
    heroUrl: '/assets/images/image-04.jpg',
    updatedLabel: '1个月前',
    tags: ['书籍', '收藏'],
    children: [],
  },
  {
    id: 5,
    name: '阁楼二区',
    type: 'room',
    path: '阁楼二区',
    itemCount: 2,
    children: [],
  },
  {
    id: 6,
    name: '办公电子设备箱',
    type: 'box',
    path: '办公室储物柜 / 二层',
    itemCount: 1,
    coverUrl: '/assets/images/image-12.jpg',
    heroUrl: '/assets/images/image-12.jpg',
    updatedLabel: '2023-10-24',
    tags: ['数码', '办公', '资产'],
    children: [],
  },
];

const items = [
  {
    id: 101,
    name: '冬季大衣',
    quantity: 3,
    locationId: 2,
    locationPath: '冬季收纳四号',
    imageUrl: '/assets/images/image-08.jpg',
    tags: ['衣物', '羊毛'],
    note: '厚羊毛 · 藏青/黑色',
    updatedLabel: '今天',
    updatedAt: '2026-06-22T02:45:00Z',
  },
  {
    id: 102,
    name: '针织围巾',
    quantity: 5,
    locationId: 2,
    locationPath: '冬季收纳四号',
    imageUrl: '/assets/images/image-09.jpg',
    tags: ['季节', '手工'],
    note: '多色 · 手工编织',
    updatedLabel: '2天前',
    updatedAt: '2026-06-20T08:00:00Z',
  },
  {
    id: 103,
    name: '皮手套',
    quantity: 2,
    locationId: 2,
    locationPath: '冬季收纳四号',
    imageUrl: '/assets/images/image-10.jpg',
    tags: ['皮革', '大号'],
    note: '棕色皮革 · 大号',
    updatedLabel: '2天前',
    updatedAt: '2026-06-19T08:00:00Z',
  },
  {
    id: 104,
    name: '保暖内衣',
    quantity: 4,
    locationId: 2,
    locationPath: '冬季收纳四号',
    imageUrl: '/assets/images/image-11.jpg',
    tags: ['保暖', '冬季'],
    note: '男女通用 · 发热面料',
    updatedLabel: '今天',
    updatedAt: '2026-06-22T02:45:00Z',
  },
  {
    id: 105,
    name: '苹果笔记本',
    quantity: 1,
    locationId: 6,
    locationPath: '办公室储物柜 · 二层',
    imageUrl: '/assets/images/image-12.jpg',
    tags: ['数码', '办公', '资产'],
    note: '电源适配器放在侧袋，包含充电线和原装保护套。',
    updatedLabel: '2023-10-24',
    updatedAt: '2023-10-24T08:00:00Z',
  },
  {
    id: 106,
    name: '大号露营灯',
    quantity: 1,
    locationId: 5,
    locationPath: '阁楼二区',
    imageUrl: '/assets/images/image-05.jpg',
    tags: ['户外', '装备'],
    note: '备用电池一起收纳。',
    updatedAt: '2026-06-18T08:00:00Z',
  },
  {
    id: 107,
    name: '四季睡袋',
    quantity: 2,
    locationId: 5,
    locationPath: '阁楼二区',
    imageUrl: '/assets/images/image-06.jpg',
    tags: ['户外', '装备'],
    note: '压缩后放在下层收纳袋。',
    updatedAt: '2026-06-18T08:00:00Z',
  },
];

const summary = {
  boxCount: 16,
  itemCount: 214,
  locationCount: 16,
  labelCount: 9,
  pendingCount: 12,
  locationDistribution: [
    { name: '客厅', count: 6, percent: 78 },
    { name: '卧室', count: 4, percent: 0 },
    { name: '阳台', count: 3, percent: 38, isBlue: true },
  ],
};

module.exports = {
  locations,
  items,
  summary,
};
